//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace KonusarakOgren.Web
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }

        public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Exam>();
                db.CreateTable<Question>();
                db.CreateTable<User>();
            }
        }
    }
    public partial class Exam
    {
        [PrimaryKey, AutoIncrement]
        [Unique(Name = "sqlite_autoindex_Exam_1", Order = 0)]
        public Int64 Id { get; set; }

        public String Title { get; set; }

        [NotNull]
        public Int64 Time { get; set; }

    }

    public partial class Question
    {
        [PrimaryKey, AutoIncrement]
        [Unique(Name = "sqlite_autoindex_Question_1", Order = 0)]
        public Int64 Id { get; set; }

        [NotNull]
        public String OptionA { get; set; }

        [NotNull]
        public String OptionB { get; set; }

        [NotNull]
        public String OptionC { get; set; }

        [NotNull]
        public String OptionD { get; set; }

        [NotNull]
        public String OptionE { get; set; }

        [NotNull]
        public String Text { get; set; }

        [NotNull]
        public Int64 ExamId { get; set; }

        [NotNull]
        public Int64 TrueOption { get; set; }

    }

    public partial class User
    {
        [PrimaryKey, AutoIncrement]
        [Unique(Name = "sqlite_autoindex_User_1", Order = 0)]
        public Int64 Id { get; set; }

        [NotNull]
        public String Username { get; set; }

        [NotNull]
        public String Password { get; set; }

    }

}
